import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Banner from "~/components/banner";
import NavBar from "~/components/nav/navBar";
import SectionCards from "~/components/sectionCards";
import { getPopularVideos, getVideos } from "~/lib/videos";
import styles from "../../styles/Home.module.css";

export type Video = {
  title: string;
  imgUrl: string;
  id: string;
};

const Home: NextPage<{
  disneyVideos: Video[];
  productivityVideos: Video[];
  travelVideos: Video[];
  popularVideos: Video[];
}> = (props) => {
  const { disneyVideos, productivityVideos, travelVideos, popularVideos } =
    props;

  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <NavBar username="ankita@ank.com" />
        <Banner
          title="Clifford the red dog"
          subTitle="a very cute dog"
          imgUrl="/static/clifford.webp"
        />

        <div className={styles.sectionWrapper}>
          <SectionCards title="Disney" videos={disneyVideos} size="large" />
          <SectionCards title="Travel" videos={travelVideos} size="small" />
          <SectionCards
            title="Productivity"
            videos={productivityVideos}
            size="medium"
          />
          <SectionCards title="Popular" videos={popularVideos} size="small" />
        </div>
      </div>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const disneyVideos = await getVideos("disney trailer");
  const productivityVideos = await getVideos("Productivity");

  const travelVideos = await getVideos("indie music");

  const popularVideos = await getPopularVideos();

  return {
    props: {
      disneyVideos,
      productivityVideos,
      travelVideos,
      popularVideos,
    },
  };
};

export default Home;
